from __future__ import annotations

from typing import Any, Literal

from .content import SchemaBase


class FunctionCall(SchemaBase):
    """
    Canonical function/tool call generated by a model.
    """

    type: Literal["function_call"] = "function_call"

    id: str | None = None

    call_id: str | None = None

    name: str

    arguments: str | dict[str, Any] = {}


class FunctionCallOutput(SchemaBase):
    """
    Result supplied to the model for a previous function call.
    """

    type: Literal["function_call_output"] = "function_call_output"

    call_id: str

    output: Any = None


class ToolCall(SchemaBase):
    """
    Generic tool call.

    Useful when a provider exposes tool calls without using
    the OpenAI function_call terminology.
    """

    type: Literal["tool_call"] = "tool_call"

    id: str | None = None

    name: str

    arguments: str | dict[str, Any] = {}


class ToolResult(SchemaBase):
    """
    Generic tool result.
    """

    type: Literal["tool_result"] = "tool_result"

    tool_call_id: str

    output: Any = None

    is_error: bool = False
