name: build

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "release/*"
      - "patch/*"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9","3.10", "3.11" ]

    steps:
      - name: Free up disk space at start
        run: |
          sudo apt clean
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ${{ matrix.python-version }}/virtualenvs/
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          pip uninstall -y pyspark
          poetry install --with dev --all-extras
          pip install pyspark==3.5.6

      - name: Check linting
        run: |
          poetry run task lint

      - name: Check formatting
        run: |
          poetry run task is-formatted

      - name: Test with pytest
        run: |
          poetry run task force-cpu-torch
          poetry run task extra-lib
          poetry run task test
